lis = [1024, 3, True, 6.5]
print(lis)
lis.append(False)
print(lis)
lis.insert(2, 4.5)
print(lis)
print(lis.pop())
print(lis)
print(lis.pop(1))
print(lis)
lis.sort()
print(lis)
lis.reverse()
print(lis)
print(lis.count(6.5))
print(lis.index(4.5))
lis.remove(6.5)
print(lis)
del lis[0]
print(lis)